# Generated by Django 2.2.1 on 2019-06-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
